name: Deploy to Production with Less.
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Create build for Less
        run: yarn build
      - name: Deploy site using Less
        env:
          LESS_TOKEN: ${{ secrets.LESS_TOKEN }}
          LESS_APPLICATION_NAME: ${{ vars.LESS_APPLICATION_NAME }}
        run: yarn deploy
